#
# Copyright (c) 2023 Siddharth Chandrasekaran <sidcha.dev@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0
#

name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.9.0
        with:
          toolchain: stable
          components: rustfmt, clippy
          target: thumbv6m-none-eabi
      - name: Cargo check
        run: cargo check
      - name: Install gcc-arm-none-eabi
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-none-eabi
      - name: Cargo check no-std
        run: cargo check --package libosdp --target thumbv6m-none-eabi --no-default-features
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.9.0
        with:
          toolchain: stable
      - name: Cargo test
        run: cargo test
